import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import { NavigationItems } from '@/components/NavigationItems';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    const token = cookies().get('token');

    return (
        <html lang='en'>
            <body className={`${inter.className} antialiased`}>
                <header className='z-10 px-5 bg-black sticky top-0'>
                    <NavigationItems token={token} />
                </header>
                {children}
            </body>
        </html>
    );
}
